services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - './localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
  app-db:
    image: postgres:15-alpine
    container_name: app-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  main-app:
    container_name: main-app
    build:
      context: ./src
      dockerfile: apps/main-app/Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - ./src/apps/main-app/.env
    environment:
      NODE_ENV: development
    volumes:
      - ./src/apps/main-app:/usr/src/apps/main-app
      - ./src/common:/usr/src/common
      - ./src/db:/usr/src/db
      - /usr/src/node_modules
    depends_on:
      app-db:
        condition: service_healthy
    command: pnpm --filter @app/main-app dev
    restart: unless-stopped
  movie-recommendation-app:
    container_name: movie-recommendation-app
    build:
      context: ./src
      dockerfile: apps/movie-recommendation-app/Dockerfile.dev
    ports:
      - '3001:3001'
    env_file:
      - ./src/apps/movie-recommendation-app/.env
    environment:
      NODE_ENV: development
    volumes:
      - ./src/apps/movie-recommendation-app:/usr/src/apps/movie-recommendation-app
      - ./src/common:/usr/src/common
      - /usr/src/node_modules
    depends_on:
      app-db:
        condition: service_healthy
    command: pnpm --filter @app/movie-recommendation-app dev
    restart: unless-stopped
  simple-messaging-app:
    container_name: simple-messaging-app
    build:
      context: ./src
      dockerfile: apps/simple-messaging-app/Dockerfile.dev
    env_file:
      - ./src/apps/simple-messaging-app/.env
    environment:
      NODE_ENV: development
    volumes:
      - ./src/apps/simple-messaging-app:/usr/src/apps/simple-messaging-app
      - ./src/common:/usr/src/common
      - /usr/src/node_modules
    depends_on:
      app-db:
        condition: service_healthy
    command: pnpm --filter @app/simple-messaging-app dev
    restart: unless-stopped
volumes:
  postgres_data:
